-- ============================================================
-- Assignment 4: AI generations + voting, with RLS locked down
-- ============================================================

-- generations: one row per AI-generated caption
create table if not exists generations (
  id bigint generated by default as identity primary key,
  creator_id uuid not null references auth.users (id) on delete cascade,
  author_name text not null default 'Anonymous',
  prompt text not null,
  caption text not null,
  upvotes integer not null default 0,
  downvotes integer not null default 0,
  created_at timestamptz not null default now()
);

-- votes: one row per (generation, user) -- a user's current vote
create table if not exists votes (
  id bigint generated by default as identity primary key,
  generation_id bigint not null references generations (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  value smallint not null check (value in (1, -1)),
  created_at timestamptz not null default now(),
  unique (generation_id, user_id)
);

-- Keep generations.upvotes/downvotes in sync with the votes table.
-- Runs as SECURITY DEFINER so it can update generations even though
-- regular users are never granted UPDATE on that table directly.
create or replace function public.refresh_generation_vote_counts()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_id bigint;
begin
  target_id := coalesce(new.generation_id, old.generation_id);

  update generations
  set
    upvotes = (select count(*) from votes where generation_id = target_id and value = 1),
    downvotes = (select count(*) from votes where generation_id = target_id and value = -1)
  where id = target_id;

  return coalesce(new, old);
end;
$$;

drop trigger if exists on_vote_change on votes;
create trigger on_vote_change
  after insert or update or delete on votes
  for each row execute function public.refresh_generation_vote_counts();

-- ------------------------------------------------------------
-- Row Level Security -- strictest policy set that still works
-- ------------------------------------------------------------

alter table posts enable row level security;        -- already on (assignment 2); re-asserted for completeness
alter table profiles enable row level security;      -- was intentionally off for assignment 3
alter table generations enable row level security;
alter table votes enable row level security;

-- profiles: a user can only ever see/edit their own row.
drop policy if exists "Users read their own profile" on profiles;
create policy "Users read their own profile" on profiles
  for select using (auth.uid() = id);

drop policy if exists "Users update their own profile" on profiles;
create policy "Users update their own profile" on profiles
  for update using (auth.uid() = id) with check (auth.uid() = id);
-- No insert policy: rows are only ever created by the SECURITY DEFINER
-- signup trigger, which bypasses RLS. No delete policy: profiles are
-- cleaned up automatically via the auth.users foreign key cascade.

-- generations: anyone can browse the feed (logged-out visitors too --
-- that's how people discover the app before signing up), but only an
-- authenticated user can post, and only as themselves. No update/delete
-- policy for end users: posts are immutable once created, and vote
-- tallies are only ever changed by the trigger above.
drop policy if exists "Anyone can read generations" on generations;
create policy "Anyone can read generations" on generations
  for select using (true);

drop policy if exists "Authenticated users can create generations" on generations;
create policy "Authenticated users can create generations" on generations
  for insert to authenticated
  with check (auth.uid() = creator_id);

-- votes: a user can only ever see, create, change, or remove their OWN
-- vote row. Nobody can read who-voted-what for other users directly --
-- the only thing exposed publicly is the aggregate tally on generations.
drop policy if exists "Users read their own vote" on votes;
create policy "Users read their own vote" on votes
  for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users cast their own vote" on votes;
create policy "Users cast their own vote" on votes
  for insert to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users change their own vote" on votes;
create policy "Users change their own vote" on votes
  for update to authenticated
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users remove their own vote" on votes;
create policy "Users remove their own vote" on votes
  for delete to authenticated
  using (auth.uid() = user_id);
