create table if not exists posts (
  id bigint generated by default as identity primary key,
  title text not null,
  body text,
  created_at timestamptz not null default now()
);

alter table posts enable row level security;

create policy "Public read access" on posts
  for select using (true);

insert into posts (title, body) values
  ('Welcome to the app', 'This is the first post, fetched live from Supabase.'),
  ('Second post', 'Another row to prove the list renders multiple items.'),
  ('Third post', 'Data is read-only for now -- no auth or writes yet.');
